package org.exoplatform.selenium.platform.plf.functional.welcomescreens;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.Utils;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.PlatformBase;
import org.openqa.selenium.By;
import org.testng.annotations.*;

/**
 * @author chinhdtt
 *
 */
public class PLF_WelcomeScreens_AccountSetup extends PlatformBase{

	ManageAccount acc; 

	@BeforeMethod
	public void beforeMethod(){
		info("Get Browser");
		initSeleniumTestWithOutTermAndCondition(driver);
		driver.get(DEFAULT_BASEURL);
		acc = new ManageAccount(driver, this.plfVersion);
	}
	@AfterMethod
	public void afterMethod(){
		info("After method");
		driver.manage().deleteAllCookies();
		driver.quit();
	}

	/**
	 * Case ID:79247.
	 * Test Case Name: Display the Account Setup screen.
	 * Case ID:79249.
	 * Test Case Name: Display information text after the label "Create an account".
	 * Case ID:79250.
	 * Test Case Name: The Field "username" is mandatory.
	 * Case ID:79251.
	 * Test Case Name: The Field "First name" is mandatory.
	 * Case ID:79252.
	 * Test Case Name: The Field "Last name" is mandatory.
	 * Case ID:79253.
	 * Test Case Name: The Field "Email" is mandatory.
	 * Case ID:79254.
	 * Test Case Name: Input different data in fields "Password" and "Confirm" on form "Create your account".
	 * Case ID:79255.
	 * Test Case Name: The Field "Password" is mandatory.
	 * Case ID:79256.
	 * Test Case Name: The Field "Confirm" is mandatory.
	 * Case ID:79315.
	 * Test Case Name: Input different data in fields "Password" and "Confirm" of root.
	 * Case ID:79257.
	 * Test Case Name: Display "root" by default in the field "Username".
	 * Case ID:79258.
	 * Test Case Name: Display information text after the label "Admin Password".
	 * Case ID:79259.
	 * Test Case Name: Submit the accounts by click on "Start".
	 * Case ID:79248.
	 * Test Case Name: Not display "Setup account" screen at second launch with the 1st time account has been setup.
	 * Case ID:79260.
	 * Test Case Name: The new user account is an administrator.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/01/09 10:00:06
	 */
	@Test (priority=0)
	public  void test01_DisplayTheAccountSetupScreen() {
		info("Test 1: Display the Account Setup screen");
		/*
		- Launch the app for the first time (/portal)
		- Check the checkbox: "I agree with these terms and conditions"
		- Click on the button "Continue"
		 *Input Data: 
		 *Expected Outcome: 
		- The Acount Setup screen is displayed
		- 2 Blocs are displayed:"Create your acoount" and "Admin password"
		- The button "Submit" is displayed		*/ 
		waitForAndGetElement(By.xpath(ELEMENT_TERM_CONDITION_BOX ));
		Utils.pause(500);
		info("Check the checkbox: I agree with these terms and conditions");
		check(ELEMENT_AGREEMENT_CHECKBOX, 2);
		info("Check Continue button is enabled.");
		waitForAndGetElement(ELEMENT_CONTINUE_BUTTON);
		click(ELEMENT_CONTINUE_BUTTON);		
		Utils.pause(500);
		info("Account Setup displays");
		waitForAndGetElement(ELEMENT_ACCOUNT_SETUP);
		waitForAndGetElement(ELEMENT_YOUR_ACCOUNT_LABEL);
		waitForAndGetElement(ELEMENT_INPUT_USERNAME);
		waitForAndGetElement(ELEMENT_FIRSTNAME_ACCOUNT);
		waitForAndGetElement(ELEMENT_LASTNAME_ACCOUNT);
		waitForAndGetElement(ELEMENT_EMAIL_ACCOUNT);
		waitForAndGetElement(ELEMENT_INPUT_PASSWORD);
		waitForAndGetElement(ELEMENT_CONFIRM_PASS_ACCOUNT);
		waitForAndGetElement(ELEMENT_ROOT_PASS_ACCOUNT);
		waitForAndGetElement(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT);
		waitForAndGetElement(ELEMENT_ADMIN_PASS_LABEL);
		waitForAndGetElement(ELEMENT_USER_ADMIN).getAttribute("value").equalsIgnoreCase("root");	
		
		/*
		- Read under "Create your account"
		 *Input Data: 
		 *Expected Outcome: 
		- An info text is displayed "This will be your primary user account" 		*/ 
		waitForAndGetElement(ELEMENT_YOUR_ACCOUNT_LABEL);
		waitForTextPresent("This will be your primary user account");
		
		/*
		- read after "Admin Password"
		 *Input Data: 
		 *Expected Outcome: 
		- An info text is displayed "Login as root user with the following password for super administrator access" 		*/ 
		waitForTextPresent("Login as root user with the following password for super administrator access");
		
		/*
		- Input valid data on each fields
		- Keep the field "username" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Username is required."		*/ 

		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("Username is required.");
		
		/*
		- Input valid data on each fields
		- Keep the field "Firstname" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "First name is required."		*/ 

		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "", true);
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("First name is required.");
		
		/*
		- Input valid data on each fields
		- Keep the field "Last name" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Last name is required."		*/ 
		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_LASTNAME_ACCOUNT, "", true);
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("Last name is required.");
		
		/*
		- Input valid data on each fields
		- Keep the field "Email" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Email is required."		*/ 
		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_EMAIL_ACCOUNT, "", true);	
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("Email is required.");
		
		/*
		- Input valid data on each fields on upper form
		- Input diffrent data in fields "Password" and "Confirm" on upper form
		- Input into fields on under form
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Password does not match the Confirm password"		*/ 
		String strPass = "gtn123";
		String strPassConf = "gtn1234";
		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_INPUT_PASSWORD, strPass, true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, strPassConf, true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		waitForTextPresent("Password does not match the Confirm password");
		
		/*
		- Input valid data on each fields
		- Keep the field "Password" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Password is required."		*/ 
		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);	
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_INPUT_PASSWORD, "", true);
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("Password is required.");
		
		/*
		- Input valid data on each fields
		- Keep the field "Confirm" empty
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Confirm is required."		*/ 

		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_ROOT_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "", true);	
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		assert waitForAndGetElement(ELEMENT_ACCOUNT_ERROR).getText().equalsIgnoreCase("Confirm is required.");
		
		/*
		- Input valid data on each fields on upper form
		- Input diffrent data in fields "Password" and "Confirm" on under form (of root)
		- Click on the button "Submit"
		 *Input Data: 
		 *Expected Outcome: 
		- A warning message is displayed: "Password does not match the Confirm password"		*/ 
		String strPassRoot = "gtngtn";
		strPassConf = "gtn123";
		type(ELEMENT_INPUT_USERNAME, "fqa", true);
		type(ELEMENT_FIRSTNAME_ACCOUNT, "FQA", true);
		type(ELEMENT_LASTNAME_ACCOUNT, "VN", true);
		type(ELEMENT_EMAIL_ACCOUNT, "fqa@exoplatform.com", true);	
		type(ELEMENT_INPUT_PASSWORD, "gtngtn", true);
		type(ELEMENT_CONFIRM_PASS_ACCOUNT, "gtngtn", true);
		type(ELEMENT_ROOT_PASS_ACCOUNT, strPassRoot, true);
		type(ELEMENT_ROOT_CONFIRM_PASS_ACCOUNT, strPassConf, true);
		click(ELEMENT_SUBMIT_BUTTON);
		Utils.pause(100);
		waitForTextPresent("Password does not match the Confirm password");
		
		/*
		- Click on the button "Start"
		 *Input Data: 
		 *Expected Outcome: 
		- The user is automatically logged in with the account created and redirected to the intranet home		*/ 
		accountSetup();	
		waitForAndGetElement(ELEMENT_HOME_PAGE);

		/*
		- Launch the app for a second time
		 *Input Data: 
		 *Expected Outcome: 
		- The screen "Terms and Conditions Agreement" is Not displayed
		- The screen "Setup account" is not displayed		*/ 	
		acc.signOut();
		waitForElementNotPresent(By.xpath(ELEMENT_TERM_CONDITION_BOX));
		acc.signIn("fqa", "gtngtn");
		/*Expected Outcome: 
			- Intranet Homepage is displayed
			- User is looged with the account created 
			- The user can see the full Administration menu
			- This user in membership:*:/platform/administrators*:/platform/web
			-contributors*:/platform:/users*:/developers		*/ 
		waitForAndGetElement(ELEMENT_CATEGORY_ADMINISTRATION);
	}

	/**
	 * Case ID:79313.
	 * Test Case Name: Not display the Account setup when the PLF is started in developer mode.
	 * Pre-Condition: *Terms and Conditions is accepted*Account is created and session has been started
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/01/09 10:00:06
	 */
	@Test(groups="pending")
	public  void test15_NotDisplayTheAccountSetupWhenThePLFIsStartedInDeveloperMode() {
		info("Test 15 Not display the Account setup when the PLF is started in developer mode");
		/*
		- Run the server with a command+ "start_eXo.bat 
		-
		-dev", for Windows+ "./start_eXo.sh 
		-
		-dev" for Linux
		 *Input Data: 
		 *Expected Outcome: 
		- The Intranet Homepage is displayed
		- The trial banner is not displayed in the footer of the page		*/

		/*
		- Open platform in browser
		 *Input Data: 
		 *Expected Outcome: 
		- The Account setup is not displayed 		*/ 
	}

	/**
	 * Case ID:94920.
	 * Test Case Name: Skip Creating account.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/01/09 10:00:06
	 */
	@Test(groups="pending")
	public  void test16_SkipCreatingAccount() {
		info("Test 17 Skip Creating account");
		/*
		- Start a fresh package
		 *Input Data: 
		 *Expected Outcome: Server is started without exception		*/
		waitForAndGetElement(ELEMENT_TERM_CONDITION_BOX);

		/*
		- Open Browser and type in address: http://<server>:8080/portal
		- Tick check
		- box to accept
		- Click Continue
		 *Input Data: 
		 *Expected Outcome: 
		- Term and Condition is accepted 
		- Move to Setup account screen		*/

		info("Check the checkbox: I agree with these terms and conditions");
		check(ELEMENT_AGREEMENT_CHECKBOX, 2);
		info("Check Continue button is enabled.");
		waitForAndGetElement(ELEMENT_CONTINUE_BUTTON);
		click(ELEMENT_CONTINUE_BUTTON);	
		Utils.pause(500);
		info("Account Setup displays");
		waitForAndGetElement(ELEMENT_ACCOUNT_SETUP);

		/*Click Skip button
		 *Input Data: 
		 *Expected Outcome: 
		- Return to login screen
		- Can log in with root/gtn here to create new account 		*/ 
		click(ELEMENT_SKIP_BUTTON);
		acc = new ManageAccount(driver, plfVersion);
		acc.signIn("root", "gtn");;		
	}

	/**
	 * Case ID:94923.
	 * Test Case Name: Not Display "Setup account" screen at the second launch with the 1st time skip setup account.
	 * Pre-Condition: 
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by chinhdtt at 2014/01/09 10:00:06
	 */
	@Test(groups="pending")
	public  void test17_NotDisplaySetupAccountScreenAtTheSecondLaunchWithThe1stTimeSkipSetupAccount() {
		info("Test 18 Not Display Setup account screen at the second launch with the 1st time skip setup account");
		/*
		- Launch the app for a first time 
		- Accept Term & condition agreement
		- Skip setting up account
		 *Input Data: 
		 *Expected Outcome: Return log in screen, can log in by default users		*/
		waitForAndGetElement(ELEMENT_TERM_CONDITION_BOX);
		info("Check the checkbox: I agree with these terms and conditions");
		check(ELEMENT_AGREEMENT_CHECKBOX, 2);
		info("Check Continue button is enabled.");
		waitForAndGetElement(ELEMENT_CONTINUE_BUTTON);
		click(ELEMENT_CONTINUE_BUTTON);	
		Utils.pause(500);
		info("Account Setup displays");
		waitForAndGetElement(ELEMENT_ACCOUNT_SETUP);
		click(ELEMENT_SKIP_BUTTON);
		acc = new ManageAccount(driver, plfVersion);
		acc.signIn("root", "gtn");

		/*
		- Restart server
		- Open application via browser
		 *Input Data: 
		 *Expected Outcome: 
		- Account Setup does not appear again
		- Log in screen is shown		*/ 
		driver.quit();
		beforeMethod();
		waitForElementNotPresent(By.xpath(ELEMENT_TERM_CONDITION_BOX));
		waitForAndGetElement(ELEMENT_SIGN_IN_BUTTON);		
	}
}